Rename symbols and files according to Time/Darkness prototype strings
pret/pmd-sky pull request #52
Opened 2023-12-28 22:42 UTC by ElectricGeorge

All symbols of known decompiled functions were renamed according to strings found in the prototypes. Functions with unknown exact names were named to be consistent in context. Some referenced asm symbols and several source and header files were also renamed. Some c files have an address appended to signify that the first function does not yet align with the file boundary. A decomp of an unknown text sprite init function at the beginning of overlay 29 (in poly_text.c) is also included.

2023-12-28 23:07 UTC, AnonymousRandomPerson requested changes

2023-12-28 23:07 UTC, AnonymousRandomPerson commented on src/dg_022E0354.c
> +#include "dg.h"
Including the address in the file name feels a bit messy for files that already have non-placeholder names. Perhaps the address can be added as a comment instead.

2023-12-29 03:41 UTC, ElectricGeorge commented
Addresses are now removed from the file names and comments have been added.

2023-12-29 03:42 UTC, AnonymousRandomPerson approved these changes

2023-12-29 18:19 UTC, merged