Disassemble more dungeon functions
pret/pmd-sky pull request #83
Opened 2024-10-22 05:35 UTC by chordtoll

2024-10-23 00:37 UTC, AnonymousRandomPerson requested changes
Looks like the Japan build doesn't match, which is causing the build failure.

2024-10-23 00:37 UTC, AnonymousRandomPerson commented on src/overlay_29_02338604.c
> +    return DUNGEON_PTR[0]->boost_hidden_stairs_spawn_chance;
This is the same between Japan and other regions, so the `#ifdef` isn't needed.

2024-10-23 02:37 UTC, AnonymousRandomPerson commented
I looked into the JP mismatch, and it's because we aren't yet sure where the dungeon struct differs between JP and other regions. Here's a commit you can use to match JP for now: https://github.com/AnonymousRandomPerson/pmd-sky/commit/0ef94e7ad80e23101ae5cf22554f5c0e2d4cd64e

2024-10-24 02:07 UTC, chordtoll commented
Thanks! That helps a lot! I'll keep in mind that we might need to move those ifdefs around in the future, and have updated my pre-pr build to build all languages.

2024-10-24 02:07 UTC, chordtoll commented on src/overlay_29_02338604.c
> +    return DUNGEON_PTR[0]->boost_hidden_stairs_spawn_chance;
Good catch! Fixed.

2024-10-24 03:13 UTC, AnonymousRandomPerson commented
Build is failing because of Wine not downloading properly, possibly due to mirrors being out of sync. This happens on occasion and should resolve itself in a while.

2024-10-24 16:21 UTC, AnonymousRandomPerson approved these changes

2024-10-24 16:21 UTC, merged